// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sngwqomrpueltynzeogj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZ3dxb21ycHVlbHR5bnplb2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Nzc1NTYsImV4cCI6MjA2NjQ1MzU1Nn0.V7GaZaMUUXyhCUFHtE9Y6AfwlvrOpdkmgfwYrjfy2-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);